version: '3.8'

services:
  postgres:
    image: postgres:latest
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d mydatabase"]
      timeout: 45s
      interval: 10s
      retries: 10
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  server:
    build: .
    ports:
      - "8000:80"
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
